#!/usr/bin/env bash
# Initialize Bashelicious

# Bashelicious aliases
alias ll="ls -FGlh"
alias la="ls -FHlha"
alias l="ls -FG"
alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
alias ..="cd .."
alias ...="cd ../.."
alias -- -="cd -"

# Bashelicious methods
function compress() { /usr/bin/tar -jcvf "$@" ;}
function decompress() { /usr/bin/tar -jxvf "$@" ;}

function parse_git_branch_and_add_brackets {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\ \[\1\]/'
}

# Bashelicious exports
export CDPATH=$CDPATH:.:~

# Color man pages:
export LESS_TERMCAP_mb=$'\E[01;31m'      # begin blinking
export LESS_TERMCAP_md=$'\E[01;31m'      # begin bold
export LESS_TERMCAP_me=$'\E[0m'          # end mode
export LESS_TERMCAP_se=$'\E[0m'          # end standout-mode
export LESS_TERMCAP_so=$'\E[01;44;33m'   # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'          # end underline
export LESS_TERMCAP_us=$'\E[01;32m'      # begin underline

# bash completion settings
bind "set completion-ignore-case on" # This ignores case in bash completion
bind "set bell-style none" # Turn off bell
bind "set show-all-if-ambiguous On" # Single tab completion

# Prompt layout
PS1="\[\e[0;32m\]\u\[\e[m\] \[\e[1;34m\]\w\[\e[m\]\[\e[1;32m\]\$(parse_git_branch_and_add_brackets) \[\e[1;32m\]\$\[\e[m\] "
