#!/usr/bin/env bash

################
# Bashelicious #
################
export BASHELICIOUS_DIR=$HOME/.bashelicious
export CDPATH=$CDPATH:.:~

function bashelicious_import() {
	[[ -f "${BASHELICIOUS_DIR}/$1" ]] && . ${BASHELICIOUS_DIR}/$1 || echo ":: Bashelicious failed to import file $1" >&2
}

# Load base files
bashelicious_import lib/vars.sh
bashelicious_import lib/alias.sh
bashelicious_import lib/misc.sh
bashelicious_import lib/functions.sh

# Load plugins
for PLUGIN in $(ls $BASHELICIOUS_DIR/plugins/*.plugin.sh)
do
	bashelicious_import plugins/$(basename $PLUGIN)
done